#!/usr/bin/env bash
#notes n things

filename="/etc/passwd"

while IFS=':' read -r username _ userid _ _ homedir _; do
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $homedir"
done < "$filename"
