#!/usr/bin/env bash
#
counter=1
while [ $counter -le 10 ]; do
  if [ $counter -eq 4 ]; then
    echo "Bad Luck"
  elif [ $counter -eq 8 ]; then
    echo "Good Luck"
  else
    echo "Best School"
  fi
  counter=$((counter+1))
done