#!/usr/bin/env bash
# blah blah blah
counter=1
while [ $counter -le 20 ]; do
  if [ $counter -eq 4 ]; then
    echo "4"
    echo "bad luck from China"
  elif [ $counter -eq 9 ]; then
    echo "9"
    echo "bad luck from Japan"
  elif [ $counter -eq 17 ]; then
    echo "17"
    echo "bad luck from Italy"
  else
    echo $counter
  fi
  counter=$((counter+1))
done
