#!/usr/bin/env bash
# some stuff

hour=0
minute=1
counter=0

while [ $counter -lt 70 ]; do
  printf "%02d:%02d\n" $hour $minute

  minute=$((minute+1))
  if [ $minute -eq 60 ]; then
    minute=0
    hour=$((hour+1))
    if [ $hour -eq 13 ]; then
      hour=0
    fi
  fi

  counter=$((counter+1))
done | head -n 70

